### PR TITLE
Fix subprocess command for mac os users

### LINKED ISSUE #9: MacOS BigSur wakepy fails with FileNotFoundError
[Errno 2] No such file or directory: 'caffeinate -d'
I believe I can fix it. PR will follow

### PR DESCRIPTION
**Pull request by matacoder**
Resolves #9
(no keep_screen_awake now woking). 
```
dev/wakepy/wakepy/__main__.py
Started wakepy. Your computer will not sleep automatically (unless battery goes under critical level)
\ [Press Ctrl+C to exit]
```

### CODE REVIEW

**Comment by np-8** [comment]
Thanks for the PR! Merged in v.0.4.2. 

By the way, have you tested that this works when `keep_screen_awake=False`? The [caffeinate](https://ss64.com/osx/caffeinate.html) docs seem to have also flags like `-i` and `-m` - do you think these could be needed?

**Comment by matacoder** [comment]
I've tested it in both scenarios. Considering other flags I believe they are not necessary but what we need are some mouse pointer mover or shift presser. I've tried some solutions but they requires tons of additional libraries.

**Comment by np-8** [comment]
Did you try simple `caffeinate -i` or `caffeinate -i -t 9999999`? Do they also require mouse movement? I would be happy to avoid adding dependencies to this project.

**Comment by matacoder** [comment]
It keeps computer awake, do not worry.
For my use case it is just not enough to be awake, you should interact with macos

**Comment by np-8** [comment]
Coming back to this just to say thanks and sorry that I could not merge this "officially" anymore as I just pulled the changes and merged locally. You probably would have got some GitHub activity points for a merge. Will try to merge the GitHub route in the future!

**Pull request closed without merging**
