### PR TITLE
macOS keep screen awake seems backwards #13 

### LINKED ISSUE #13: macOS keep screen awake seems backwards
It looks like the code for keeping the screen awake is backwards. See the details for caffinate:

**-d      Create an assertion to prevent the display from sleeping**

And the code (ARGS is `-d -u`):

```python
    if keep_screen_awake:
        global _process
        _process = Popen([COMMAND], stdin=PIPE, stdout=PIPE)
    else:
        _process = Popen([COMMAND] + ARGS, stdin=PIPE, stdout=PIPE)
```

It's sending -d -u if we do NOT want to keep the screen awake. I'll send a PR.

### PR DESCRIPTION
**Pull request by mikeckennedy**
Fixes #13. I'm not sure why this is including files from the last PR even though I synced the fork back. Feel free to adjust as needed.

### CODE REVIEW

**Comment by mikeckennedy** [comment]
Oh, I see why the files are out of sync in the PR. The other PR https://github.com/np-8/wakepy/pull/12 was closed even though it was merged? This should probably work but let me know.

**Comment by np-8** [comment]
Yeah I also checked the git history and saw that you had continued from the newest commit (`bbb0db8`). I think it should be fine. Not sure what is wrong, but perhaps it has something to do with the merge.  ¯\_(ツ)_/¯

I wait your comments about possible inclusion of the `-t 999999` . I have no Mac so I cannot test the solution.

**Comment by mikeckennedy** [comment]
I agree. Not sure why but my updates don't propagate here. So I'll close this and do a new PR.

**Comment by mikeckennedy** [comment]
See https://github.com/np-8/wakepy/pull/15

**Pull request closed without merging**
